datasources:
  default:
    url: jdbc:postgresql://localhost:5432/spring-guides
    driverClassName: org.postgresql.Driver
    username: postgres
    password: example
    schema-generate: CREATE_DROP
    dialect: POSTGRES