# list all notes
curl -s http://localhost:8080/v1/notes

# list specific notes by id
curl -s http://localhost:8080/v1/notes?id=<id1>&id=<id2>

# add new note
curl -s -X PUT http://localhost:8080/v1/notes --json '{"title": "curl`s --json flag","body": "Use `--json` flag to avoid setting content-type and accept headers","createdBy": "@anya","readOnly": false}'

# upload a note
curl -s http://localhost:8080/v1/notes -F "title=Paste to clipboard on macOS" -F "body=@sample.md;type=text/markdown" --form-string "createdBy=@nare" -F "readOnly=false"

# patch an existing note
curl -s -X PATCH http://localhost:8080/v1/notes --json '{"readOnly": true,"id": <id>}'

# delete notes by id
curl -s -X DELETE http://localhost:8080/v1/notes/<id1>,<id2>
