services:
  localstack:
    container_name: localstack-with-aws-cli
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"