spring:
  datasource:
    password: stacy
    username: gwen
    url: jdbc:postgresql://localhost:5432/brooklyn
  sql.init.mode: always

openapi:
  info:
    title: "Notes API"
    description: "A demo of Springdoc integration with custom configuration"
    version: "@project.version@"
    license:
      name: MIT
      url: "https://opensource.org/licenses/MIT"
  security:
    - BearerToken:
  components:
    security-schemes:
      BearerToken:
        name: BearerToken
        type: HTTP
        scheme: bearer
        bearer-format: JWT
