version: '3'

services:
  greeter-ui:
    image: mflash/greeter-ui
    networks:
      - greeternet
    ports:
      - 4200:4200

  greeter-api:
    image: mflash/greeter-api
    networks:
      - greeternet

networks:
  greeternet:
    driver: bridge