version: '3'

services:

  mongo:
    image: mongo:latest
    container_name: mongodb_latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: gwen
      MONGO_INITDB_ROOT_PASSWORD: stacy
